POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "User id is sent along the request",
    "author": "someone important",
    "url": "some url",
    "likes": 100,
    "userId": "63836b0dc59acbc1d546500e"
}
